### ISSUE TITLE
Cannot access menu items of MRI on LibreOffice 6.0

### ISSUE THREAD

**Issue by luane-aquino** [hanya/MRI#17]
Hi,

I have installed MRI 1.3.3 on LibreOffice 6.0.7.3, but the menu items doesn't show up.

![screenshot](https://user-images.githubusercontent.com/10707843/63657129-b1355000-c76b-11e9-93e8-30f9fd3fbb4f.png)

*What I already tried without success:
- Updated Python to version 3.7
- Installed others versions of MRI (1.3.4, 1.3.1)

The operating system I am using is Ubuntu 18.04.9.

I appreciate any help, Thank you.

**Comment by ghost** [comment]
Pleas, update LibreOffice, work fine in 6.2+

**Comment by DonaldSch** [comment]
Actually I have the same problem in LO 6.3.4.2 using Manjaro Linux

**Comment by DonaldSch** [comment]
Also have the problem in LO6.4.0.2

**Comment by ghost** [comment]
Tested in LibO 6.3.4.2, in ArchLinux, work fine

![mri](https://user-images.githubusercontent.com/636253/72658691-13405d00-397a-11ea-8377-78a8e1e54c16.png)

**Comment by ghost** [comment]
Tested in Libo 6.4 in Arch, work fine too.

![Screenshot from 2020-01-17 22-41-45](https://user-images.githubusercontent.com/636253/72658710-9feb1b00-397a-11ea-85a9-bf9613e0592b.png)

**Comment by DonaldSch** [comment]
Thank you. I found that it happens under KDE but I can set an environment
variable to use gtk(export SAL_USE_VCLPLUGIN=gtk3; libreoffice6.4), in
which case menus work.

thanks again
Donald

**Comment by luane-aquino** [comment]
After I updated libreOffice, it worked, thanks!
