### ISSUE TITLE
Menu not clickable on LO 24.2.0.3

### ISSUE THREAD

**Issue by akrogun** [hanya/MRI#22]
Hi, I want to report that menus can not been click.
Using MRI 1.3.3 or 1.3.4 on LibreOffice 24.2. On LibreOffice 7.3.7 works just fine.

**Comment by akrogun** [comment]
I found these packages ruin MRI menus:
libreoffice-kf5
libreoffice-qt5
libreoffice-plasma

If I not mistake, MRI using gtk3 to run properly? But, in other hand, gtk3 can no show fully dark mode in LibreOffice, background of toolbars still in light bright color. How to fix that?

FYI, my system are:
Operating System: Kubuntu 22.04.4 LTS
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-25-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-4170 CPU @ 3.70GHz
Memory: 7,7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4400

**Comment by hanya** [comment]
MRI creates window including its menu bar through Office API.
The menubar is generated by the same mechanism used in the other part of the office.
I think it could not be fixed by the MRI itself.
