### ISSUE TITLE
Even the MRI-1.3.1.oxt doesn't work in LO 5.1

### ISSUE THREAD

**Issue by richierh** [hanya/MRI#6]
I tried to install every version of MRI until the latest one (MRI-1.3.1). It doesn't show anything after I click the MRI tools , (either in the basic IDE or in the add-ons --> MRI Tools).I had installed all the package properly and there was no error on the system and in the installed LO at all ..
 
I am suspicious on the package code that is not suitable anymore with the newest LO. but I had no programming skill with it. So please, fix this bug so I can use it again...

I am sorry if my english in bad, It is not my native language

**Comment by hanya** [comment]
Please use version 1.3.2 or later.

**Comment by richierh** [comment]
I had finally succeed to install MRI version 1.3.2, tks


On Wed, 13 Apr 2016 23:58:23 -0700
hanya <notifications@github.com> wrote:

> Please use version 1.3.2 or later.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/hanya/MRI/issues/6#issuecomment-209788807


-- 
Richie <pmc.computer@yahoo.com>
