### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by TopView** [hanya/MRI#7]
https://github.com/hanya/MRI/wiki/Installation says: "Install MRI extension package using Extension Manager from Tools - Extension Manager entry of main menu bar."  

So I open LO, and go to Tools | Extension Manager and search for MRI and click on it, and it says only: "**Install Instructions**, Fill in the install instructions".  Hun?

Furthermore, the LO Tools | Extension manager | Help  button is not working.  (https://bugs.documentfoundation.org/show_bug.cgi?id=104404).

So to help the next guy, here are two links to LO Extension Installation instructions:
* https://wiki.documentfoundation.org/Documentation/HowTo/install_extension
* https://www.libreoffice.org/assets/Uploads/EN-Documents/Installingextensions.odt

**Comment by hanya** [comment]
Download extension package and install through Tools - Extension Manager. You have to choose the OXT package you have downloaded on the manager window.

**Comment by TopView** [comment]
Thanks.  I noticed I could update the wiki here, so I did.  And thanks for MRI, it look like just what I was looking for!  My hat is off to you for creating it.
